### PR TITLE
fix(deisctl): fix deisctl ssh <cmd> output

### LINKED ISSUE #4232: Inaccurate output: executing on "container"
```
$ deisctl ssh controller echo foo
Executing 'echo foo' on container 'controller'
foo
```

> ```
Executing 'echo foo' on container 'controller'
```

That is not an accurate statement.  The command is executing remotely on the host that is hosting that container.  The hostname should probably be shown instead.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #4232

### CODE REVIEW

**Comment by mboersma** [comment]
Code LGTM.

File: deisctl/backend/fleet/ssh.go [hunk 1]
```diff
@@ -25,24 +25,25 @@ func (c *FleetClient) SSH(name string) error {
...
 func (c *FleetClient) SSHExec(name, cmd string) error {
-	fmt.Printf("Executing '%s' on container '%s'\n", cmd, name)
 
-	conn, err := c.sshConnect(name)
+	conn, ms, err := c.sshConnect(name)
 	if err != nil {
 		return err
 	}
 
+	fmt.Printf("Executing '%s' on %s\n", cmd, ms.PublicIP)
```
Comment (bacongobbler) [inline deisctl/backend/fleet/ssh.go]: should this be printed to stderr?

**Comment by bacongobbler** [comment]
code LGTM anyways, since the behaviour is the same as it was.
