### PR TITLE
fix(buidler): Fix problem with missed git repos after builder restart

### LINKED ISSUE #3458: /home/git/project.git/hooks/pre-receive: No such file or directory
Uh. I tried to push a new version to Deis. Mid-push my computer shut down, and when I returned I could not push again because a push was in progress.

I read in the issue tracker that you could a) delete the lock file or b) restart the builder. I didn't find any lockfile, so I restarted the builder.

Now it seems like nothing works.

I get this error when pushing

```
onbjerg at AIR in ~/Projects/wallz on develop
$ git push deis develop:master
/usr/local/bin/gitreceive: line 33: /home/git/wallz.git/hooks/pre-receive: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

### PR DESCRIPTION
**Pull request by rvadim**
Resolve #3458
Just handle situation when /home/git/app.git/ contains only cache and build dir.

### CODE REVIEW

**Comment by carmstrong** [comment]
Thanks for the work on this, @rvadim!

**Comment by nathansamson** [comment]
Any chance for this to be merged in for 1.12.0/ 1.12.1? This hit me again yesterday which is kinda annoying...

**Comment by carmstrong** [comment]
> Any chance for this to be merged in for 1.12.0/ 1.12.1?

I think we're waiting for @krancour et. al. to confirm this resolves #3458. Unfortunately, unlikely to make 1.12 at this point, although certainly a candidate for 1.12.1

File: builder/git/git.go [hunk 1]
```diff
@@ -177,37 +201,31 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
+				return true, nil
+			} else {
+				log.Warnf(c, "Path '%s' have not config file, remove it and recreate.", repoPath)
+				if err := os.RemoveAll(repoPath); err != nil {
+					return false, fmt.Errorf("Unable to remove path '%s': %s", repoPath, err)
+				}
+				return initRepo(repoPath, gitHome, c)
+			}
+		} else {
+			log.Warnf(c, "Path '%s' not a directory, remove it and recreate.", repoPath)
```
Comment (krancour) [inline builder/git/git.go]: Can we please change this to:

```
log.Warnf(c, "Path `%s` is not a directory; removing it and recreating.", repoPath)
```

File: builder/git/git.go [hunk 2]
```diff
@@ -177,37 +201,31 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
-			log.Warnf(c, "Failed to create repository: %s", err)
-			return false, err
+	if fi, err := os.Stat(repoPath); err == nil {
+		if fi.IsDir() {
+			configPath := filepath.Join(repoPath, "config")
+			if _, cerr := os.Stat(configPath); cerr == nil {
+				log.Infof(c, "Directory '%s' already exists.", repoPath)
+				return true, nil
+			} else {
+				log.Warnf(c, "Path '%s' have not config file, remove it and recreate.", repoPath)
```
Comment (krancour) [inline builder/git/git.go]: Can we please change this to:

```
log.Warnf(c, "No config file found at path `%s`; removing it and recreating.", repoPath)
```

File: builder/git/git.go [hunk 3]
```diff
@@ -177,37 +201,31 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
-			return true, err
-		}
-		ioutil.WriteFile(filepath.Join(repoPath, "hooks", "pre-receive"), hook, 0755)
-
-		return true, nil
-	} else if err == nil {
-		return false, errors.New("Expected directory, found file.")
-	} else {
-		return false, err
+	} else if err != nil {
```
Comment (krancour) [inline builder/git/git.go]: Should be using `os.IsNotExist(err)` to isolate when the file doesn't exist vs. some other unanticipated error.

File: builder/git/git.go [hunk 4]
```diff
@@ -177,37 +201,31 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
+			configPath := filepath.Join(repoPath, "config")
+			if _, cerr := os.Stat(configPath); cerr == nil {
+				log.Infof(c, "Directory '%s' already exists.", repoPath)
+				return true, nil
+			} else {
+				log.Warnf(c, "Path '%s' have not config file, remove it and recreate.", repoPath)
+				if err := os.RemoveAll(repoPath); err != nil {
+					return false, fmt.Errorf("Unable to remove path '%s': %s", repoPath, err)
+				}
+				return initRepo(repoPath, gitHome, c)
```
Comment (krancour) [inline builder/git/git.go]: There are many calls to `initRepo()` in the various branches of this conditional.  Move this to the end, after the conditional, since most paths need to result in this.  Paths that do not can just return early.

**Comment by krancour** [comment]
Overall, this looks like a nice improvement.  See some of my comments in-line requesting minor cleanup.  I still need to test this manually, but I would say this looks very promising.

**Comment by krancour** [comment]
I cannot seem to reproduce #3458 today on Vagrant or AWS.  I have tried v1.11.2 and v1.10.0.  Without reproducing, it's for me to say this has solved anything-- altho the code looks promising.  @rvadim has this definitely resolved the issues that you were seeing in your cluster?

**Comment by krancour** [comment]
@rvadim typo in commit message also needs to be fixed.  Change "buidler" to "builder".  (Want to keep commit history grepable by component.)

**Comment by krancour** [comment]
I've spent all day on this and one thing I have discovered is that I can reproduce this using version 1.11.2 or prior, but I can't reproduce it with the code that's currently in the master branch-- and that's code that does _not_ include this PR.  I strongly believe that something else that went in recently inadvertently resolved #3458 altho I am not yet sure what.  cc @technosophos @mboersma

**Comment by krancour** [comment]
Using `git bisect`, it would seem that #4671 inadvertently fixed the issue.  I'm not at all sure why.

**Comment by rvadim** [comment]
Since apply this patch to builder, no more requests with "unable to deploy, git ..." from our cluster users. (v1.10.0 and v1.11.2)

**Comment by krancour** [comment]
@rvadim would you mind trying using the builder from master and let me know what you find?  Using what's currently in master (i.e. 1.12.0-dev) I don't see any issues.

**Comment by rvadim** [comment]
In fact, this part of builder is risky, in my opinion, we need to fix it in any way.
@krancour ok, i will try to check version of builder from master. It takes 2 - 4 hours

**Comment by krancour** [comment]
@rvadim, we appreciate all the efforts.  2 - 4 hours seems high.  Just in case you were not aware... you don't need to build and deploy the whole platform from source.  If you have a cluster going already, you can build and deploy just the builder component with:

```
$ make -C builder build deploy
```

**Comment by rvadim** [comment]
At this moment i can't reproduce this on master branch builder.

**Comment by krancour** [comment]
@rvadim thanks for checking.  I'm going to move the discussion back to #3458 as there were more participants there.  I'm curious to see what results the rest of them have with the builder from master.

**Comment by krancour** [comment]
@rvadim since there's been no luck in you or me or anyone else identifying the root cause and despite thinking that #4671 inadvertently fixed this, I think this PR (which treats the symptom, really) still contains some positive improvements and a nice fail-safe in case the problem isn't already quite as fixed as we think/hope it is.  I do want to merge this...

If you would be so kind, please squash the two commits (and reword to fix spelling of "buidler" to "builder") and this then gets my LGTM.

Really appreciate your hard work on this issue.  I owe you a :beer:

**Comment by bacongobbler** [comment]
no kill like overkill :+1:

**Comment by rvadim** [comment]
Done. I fixed typo and recheck all cases with last changes. Thank you.

**Comment by krancour** [comment]
@rvadim thank you very much!

File: builder/git/git.go [hunk 5]
```diff
@@ -177,37 +201,30 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
-			log.Warnf(c, "git init output: %s", out)
-			return false, err
-		}
-
-		hook, err := prereceiveHook(map[string]string{"GitHome": gitHome})
-		if err != nil {
-			return true, err
+	if fi, err := os.Stat(repoPath); err == nil {
+		if fi.IsDir() {
+			configPath := filepath.Join(repoPath, "config")
```
Comment (bacongobbler) [inline builder/git/git.go]: wouldn't config be in `filepath.Join(repoPath, ".git", "config")`?

Comment (bacongobbler) [inline builder/git/git.go]: Ah never mind, I see that's already added to the path [here](https://github.com/deis/deis/blob/29b6c0b2aab51739cd2a128f7fd5dbbb6b305809/builder/git/git.go#L93).

File: builder/git/git.go [hunk 6]
```diff
@@ -177,37 +201,30 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
+			if _, cerr := os.Stat(configPath); cerr == nil {
+				log.Infof(c, "Directory '%s' already exists.", repoPath)
+				return true, nil
+			} else {
+				log.Warnf(c, "No config file found at path `%s`; removing it and recreating.", repoPath)
```
Comment (bacongobbler) [inline builder/git/git.go]: we should print configPath here instead

File: builder/git/git.go [hunk 7]
```diff
@@ -177,37 +201,30 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
+				return false, fmt.Errorf("Unable to remove path '%s': %s", repoPath, err)
+			}
 		}
-		ioutil.WriteFile(filepath.Join(repoPath, "hooks", "pre-receive"), hook, 0755)
-
-		return true, nil
-	} else if err == nil {
-		return false, errors.New("Expected directory, found file.")
+	} else if os.IsNotExist(err) {
+		log.Infof(c, "Unable to get stat for path '%s': %s .", repoPath, err)
```
Comment (bacongobbler) [inline builder/git/git.go]: Let's put this one at `log.Debugf()`. It's not an error (we're going to create this directory), but it's still useful information for debugging.

File: builder/git/git.go (hunk 6 above)
Comment (krancour) [inline builder/git/git.go]: Partially agree.  Changing that would muddy the second half of the statement-- the "removing it and recreating" part.  Maybe better wording would be:

```
log.Warnf(c, "No config file found in repo at `%s`; removing it and recreating.", repoPath)
```

File: builder/git/git.go (hunk 7 above)
Comment (krancour) [inline builder/git/git.go]: ack

**Comment by krancour** [comment]
@rvadim can you make the two small changes mentioned above?  And then I think this would be good to go.

File: builder/git/git.go [hunk 8]
```diff
@@ -177,37 +201,30 @@ func createRepo(c cookoo.Context, repoPath, gitHome string) (bool, error) {
...
-		}
-
-		hook, err := prereceiveHook(map[string]string{"GitHome": gitHome})
-		if err != nil {
-			return true, err
+	if fi, err := os.Stat(repoPath); err == nil {
+		if fi.IsDir() {
+			configPath := filepath.Join(repoPath, "config")
+			if _, cerr := os.Stat(configPath); cerr == nil {
+				log.Infof(c, "Directory '%s' already exists.", repoPath)
```
Comment (krancour) [inline builder/git/git.go]: This should be `log.Debugf` instead.  Creating a new dir (as on line 172) is good info to log.  The fact that we _don't_ need to create a new dir is generally extraneous info that one would only want to see during debugging, I imagine.

**Comment by rvadim** [comment]
Fixed

**Comment by krancour** [comment]
Ping @bacongobbler.  Can you give this a second glance when you have a chance?

**Comment by krancour** [comment]
@rvadim thanks!  We're just about there.

**Comment by bacongobbler** [comment]
conference internet is best internet
