### PR TITLE
fix(deisctl): hide random "deis-" services from "deisctl list"

### LINKED ISSUE #3232: bug(deisctl): list should not show apps with the pattern name ^deis-*
If exists an app with the name `deis-demo` it will appear in the output of `deisctl list`

### PR DESCRIPTION
**Pull request by mboersma**
Closes #3232.

### CODE REVIEW

File: deisctl/backend/fleet/list_units.go [hunk 1]
```diff
@@ -82,8 +104,11 @@ func (c *FleetClient) ListUnits() (err error) {
 	}
 
 	for _, us := range unitStates {
-		if strings.HasPrefix(us.Name, "deis-") {
-			states = append(states, us)
+		for _, prefix := range unitPrefixes {
```
Comment (bacongobbler) [inline deisctl/backend/fleet/list_units.go]: sad that there's no `in` clause for Go. :(

**Comment by bacongobbler** [comment]
LGTM

File: deisctl/backend/fleet/list_units.go (hunk 1 above)
Comment (mboersma) [inline deisctl/backend/fleet/list_units.go]: I thought about making the data structure a Go `map` with empty values just so I wouldn't have to add another loop, but that sounded wrong. I'm assuming this code is more or less optimal after the compiler is done with it. :)

Comment (bacongobbler) [inline deisctl/backend/fleet/list_units.go]: The only way I could think we could optimize it would be to use `for i := range unitPrefixes { fmt.Println(unitPrefixes[i]) }` which would only allocate the iterator, but then we'd be using it to access the value anyways... meh. The Go std lib uses both ways as well so it's tomato vs tomatoe. I like this approach better, anyways :+1:

File: deisctl/backend/fleet/list_units.go [hunk 2]
```diff
@@ -72,6 +72,28 @@ var (
 	}
 )
 
+// unitPrefixes are compared to unit names, so "deisctl list" doesn't show "deis-demo.service",
+// for example. Update this list when adding a new Deis unit file.
+var unitPrefixes = []string{
```
Comment (carmstrong) [inline deisctl/backend/fleet/list_units.go]: Could we pull this into a global variable? It'd be nice to have one master list we could use here and in refreshUnits.

Comment (mboersma) [inline deisctl/backend/fleet/list_units.go]: I did look at using a single data structure for exactly that purpose, but the Go packages that would consume it don't have any common imports. I'll take another look at it tomorrow--it would be lame to maintain essentially the same data in both places.

**Comment by mboersma** [comment]
I updated this to move the unit file names to a common package. I put `units.go` into the units/ dir, which holds the actual unit files but wasn't a go package before.

**Comment by carmstrong** [comment]
Love the change to use the new units! Code LGTM.
