### PR TITLE
fix(client): suggest help when git remote creation fails

### LINKED ISSUE #4455: Creating an app when deis remote already exists
'deis create' when a deis remote already exists bubbles up the git error that says the remote called deis already exists. 
It'd be nice to have an more clear error/warning like “Existing deis remote already exists. The app was created, but a git remote couldn’t be created. Remove the git remote and add the new one with <command>"

### PR DESCRIPTION
**Pull request by mboersma**
```console
$ deis create
Creating Application... done, created madras-yachting
fatal: remote deis already exists.
To replace the existing git remote entry, run:
  git remote rename deis deis.old && deis git:remote -a madras-yachting
Error: exit status 128
```

Closes #4455.

cc: @michelleN, let me know if this is what you had in mind.

### CODE REVIEW

File: client/cmd/apps.go [hunk 1]
```diff
@@ -46,7 +46,13 @@ func AppCreate(id string, buildpack string, remote string, noRemote bool) error
 	}
 
 	if !noRemote {
-		return git.CreateRemote(c.ControllerURL.Host, remote, app.ID)
+		if err = git.CreateRemote(c.ControllerURL.Host, remote, app.ID); err != nil {
+			if err.Error() == "exit status 128" {
+				fmt.Println("To replace the existing git remote entry, run:")
```
Comment (carmstrong) [inline client/cmd/apps.go]: Should we also say something like "A remote for Deis already exists"?

Comment (mboersma) [inline client/cmd/apps.go]: Git itself said that immediately before we print this: `fatal: remote deis already exists.`

Comment (carmstrong) [inline client/cmd/apps.go]: :+1:

**Comment by michelleN** [comment]
Thanks @mboersma that's perfect :) :+1:
